### ISSUE TITLE
the code writes the tendermint config.toml and genesis.json

### ISSUE THREAD

**Issue by greg-szabo** [nomic-io/nomic#104]
I've never heard of an ABCI app _writing_ the Tendermint `config.toml` let alone using _hard-coded values_.

Please add an option to `nomic start` that reads the config, checks its values against the hard-coded expectations and panics (possibly with what does not match) instead of overwriting values in `config.toml`.

Operationally speaking the input should not be mangled this way by the binary because the `config.toml` is supposed to be managed by the operator.

The case of `genesis.json` is even worse: the file is only read at the first startup of tendermint and completely ignored otherwise. However because of the way the Rust binary _writes_ the `genesis.json`, in certain operations the binary can simply fail (with a permission denied).

User story: I'm using Kubernetes/HashiCorp Nomad to run the nomic binary. The `config.toml` and `genesis.json` files are binded into the Docker image hence they cannot be deleted. However the Rust `std::io::write` function calls an underlying logic in Linux that fails with Permission denied if the file is a file system device and not a regular file.

The source code should consider these files read-only in all cases.

**Comment by greg-szabo** [comment]
Oh, also, we found that the seeds parameter and the state sync is overwritten with unknown third-party IP addresses. There is no documentation about whose nodes those are and what security measures are in place there.

**Comment by mappum** [comment]
Writing these files is part of the initialization process, similar to `tendermint init`, we should ensure the process doesn't modify the config unless using an option that clearly does so or on the first run. This makes the experience of running a node much easier by default for the average user.

To support your kind of setup, we should have a CLI option to skip the initialization step, expecting to already be configured by the user.

**Comment by mappum** [comment]
We've taken this feedback to heart and will now always abide by never modifying config.toml/genesis.json except when initializing (e.g. they did not exist prior to running the command), or when running a command where the user is clearly and explicitly trying to modify them (e.g. `nomic config set p2p.seeds "xyz"`.
