### ISSUE TITLE
Feature Request: --node Parameter

### ISSUE THREAD

**Issue by AgoraNodes** [nomic-io/nomic#108]
Hello!

Currently we are using a different port to run Nomic on. As a result we have to make changes to config.toml which is fine. But when making queries, it defaults to the address specified in `src/bin/nomic.rs`. So currently we have to make changes and rebuild the binary. It would be nice if we had a --node parameter, or if we were able to set the node with something like `nomic config node 127.0.0.1:26698` for example. Or alternatively have the parameter captured from config.toml. Just thinking out loud. In any case, we think this could be a very useful feature for Nomic :)

**Comment by mappum** [comment]
Duplicate of #88
