### ISSUE TITLE
Validator consensus key and identity.

### ISSUE THREAD

**Issue by kicknoob** [nomic-io/nomic#109]
Goodmorning. I have some issue finding the validator consensus key and the identity for my node. I have read the line from the readme doc, but i don't know how to find the validator key from the output of http://localhost:26657/status. I literally don't know what should i do in this case on ubuntu konsole. 
Same thing for the identity. I don't know what is a Keybase profile.

**Comment by mappum** [comment]
>i don't know how to find the validator key from the output of http://localhost:26657/status

In the status output, you can search for `pub_key`, following that you should see `"value": "..."` - the consensus key is the value string in the quotes. In future versions, we can make the CLI get this automatically.

>I don't know what is a Keybase profile.

Keybase can be found here: https://keybase.io/, you can sign up and create a profile.
