### ISSUE TITLE
delegate doesn't work

### ISSUE THREAD

**Issue by Kwaskoff** [nomic-io/nomic#117]
This is screenshot and console error of redelegation.

![image](https://user-images.githubusercontent.com/15308024/178788725-758c7297-2498-4fad-afff-97a7b5c5c3ae.png)
response: {"code":1,"codespace":"","data":"","gas_used":"0","gas_wanted":"0","height":"0","info":"","logs":["Call Error: Coins Error: Insufficient balance"],"raw_log":"[]","timestamp":"","tx":null,"txhash":"41B61CCA0BF5BE9AB6A1DEB08902154B4559A8E149D1316B8D74480C3D194F27"}

Delegate has the same error

p.s. Build binary in release, please

**Comment by mappum** [comment]
This is a bug in the UI, but you just need to delegate at least 0.01 NOM less than your balance (to account for the fee).
