### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'Could not get tendermint block header: response error

### ISSUE THREAD

**Issue by Femkecl** [nomic-io/nomic#123]
Was trying to set up a node for testnet. This is the error i received.

Caused by:
    Internal error: min height 2 can't be greater than max height 0 (code: -32603)

Location:
    /home/sentinel/.cargo/registry/src/github.com-1ecc6299db9ec823/flex-error-0.4.4/src/tracer_impl/eyre.rs:10:9', src/bin/nomic.rs:316:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
App Error: panic

**Comment by Cordtus** [comment]
See previous issue

**Comment by Femkecl** [comment]
> See previous issue

It's not the same issue. This issue happens on testnet and there is no line of editing out the said node.

**Comment by Femkecl** [comment]
Solved. Statesync server was down
