### ISSUE TITLE
nomic don't respect config.toml

### ISSUE THREAD

**Issue by ichthyx** [nomic-io/nomic#137]
Changing rpc.laddr port (or address) in config.toml

Then nomic balance the nomic bin is trying to use 127.0.0.1:26657 which was another node and make nomic going total crazy

If I remove the other (tendermint cosmos node) 

this error happen :

HTTP error

Caused by:
    error trying to connect: tcp connect error: Connection refused (os error 111)

**Comment by mappum** [comment]
Duplicate of #88
