### ISSUE TITLE
Compile Error Ubuntu

### ISSUE THREAD

**Issue by Franzferdinan51** [nomic-io/nomic#141]
so im having an issue where at the very end of the compile it fails complains about orga macros ive looked everywhere but info seems limited ill post the error below hopefully someone can help me out so i can get my node running

<img width="606" alt="image" src="https://user-images.githubusercontent.com/781758/216018423-4a50245c-32c4-49ac-a718-2ddf166b20b2.png">

   Compiling wasm-bindgen-macro v0.2.79
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /root/.cargo/git/checkouts/orga-93bd515e30e7ca9a/cc9356d/macros/src/lib.rs:1:12
  |
1 | #![feature(proc_macro_span)]
  |            ^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /root/.cargo/git/checkouts/orga-93bd515e30e7ca9a/0f3b1c8/macros/src/lib.rs:1:12
  |
1 | #![feature(proc_macro_span)]
  |            ^^^^^^^^^^^^^^^

   Compiling rustls-native-certs v0.5.0
For more information about this error, try `rustc --explain E0554`.
error: could not compile `orga-macros` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `orga-macros` due to previous error
error: failed to compile `nomic v3.0.0 (/home/duckets/nomic)`, intermediate artifacts can be found at `/home/duckets/nomic/target`
duckets@duckets-MS-7C37:~$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/duckets/snap/rustup/common/rustup

installed toolchains
--------------------

nightly-2022-02-02-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (directory override for '/home/duckets')
rustc 1.69.0-nightly (dc1d9d50f 2023-01-31)

**Comment by mappum** [comment]
Not sure if you ever resolved your issue, but it seems to be something related to your rust toolchain install rather than something with the nomic codebase (since the errors are implying the build is attempting to use stable Rust). Let us know if you're still having issues and we can help debug.
