### ISSUE TITLE
'nomic validators' command: validator's commission not returned

### ISSUE THREAD

**Issue by zenchainlabs** [nomic-io/nomic#90]
The `nomic validators` command currently does not return the validator's commission_rate. Can this be added to the results of the command? Folks building explorer interfaces as well as potential delegators will find it useful to list each validator's commission beside their other details.

https://github.com/nomic-io/nomic/blob/4aa1d001210f080cc12012eb7593c66340fc7cb3/src/main.rs#L199

**Comment by zenchainlabs** [comment]
Created a PR for this: https://github.com/nomic-io/nomic/pull/89

**Comment by mappum** [comment]
Closing since the PR is merged
